name: aloria
description: Aloria Flutter app skeleton
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  web_socket_channel: ^2.4.5

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lessons/
    - assets/lessons/trading-basics/
    - assets/lessons/investing-basics/
